insert into Tags (name) values ('UI');
insert into Tags (name) values ('Front-end code');
insert into Tags (name) values ('Golang');
insert into Tags (name) values ('C#');
insert into Tags (name) values ('C++');
insert into Tags (name) values ('Design');
insert into Tags (name) values ('Bugfixing');
insert into Tags (name) values ('UML-diagram');
insert into Tags (name) values ('ER-diagram');
insert into Tags (name) values ('Java');
insert into Tags (name) values ('JavaScript');
insert into Tags (name) values ('Requirement Elicitation');
insert into Tags (name) values ('Security');
insert into Tags (name) values ('Improvement');
insert into Tags (name) values ('Feature');
insert into Tags (name) values ('Innovate');