insert into MOCK_DATA (tagId, tagName) values (1, 'UI');
insert into MOCK_DATA (tagId, tagName) values (2, 'Front-end code');
insert into MOCK_DATA (tagId, tagName) values (3, 'Golang');
insert into MOCK_DATA (tagId, tagName) values (4, 'C#');
insert into MOCK_DATA (tagId, tagName) values (5, 'C++');
insert into MOCK_DATA (tagId, tagName) values (6, 'Design');
insert into MOCK_DATA (tagId, tagName) values (7, 'Bugfixing');
insert into MOCK_DATA (tagId, tagName) values (8, 'UML-diagram');
insert into MOCK_DATA (tagId, tagName) values (9, 'ER-diagram');
insert into MOCK_DATA (tagId, tagName) values (10, 'Java');
insert into MOCK_DATA (tagId, tagName) values (11, 'JavaScript');
insert into MOCK_DATA (tagId, tagName) values (12, 'Requirement Elicitation');
insert into MOCK_DATA (tagId, tagName) values (13, 'Security');
insert into MOCK_DATA (tagId, tagName) values (14, 'Improvement');
insert into MOCK_DATA (tagId, tagName) values (15, 'Feature');
insert into MOCK_DATA (tagId, tagName) values (16, 'Innovate');